### PR TITLE
nix: default ghc to version 9.6.3

### PR DESCRIPTION
**Pull request by mgmeier**
# Description

This PR adds GHC 9.6.3 via `haskell.nix` to CI.

### CODE REVIEW

**Comment by angerman** [comment]
I finally found the culprit:
```
    -- GHC 9.4.5, 9.6.1, and 9.6.2 on Windows do not link against mingwex, but
    -- unix-time implicitly depends on this library due to the use of the
    -- gettimeofday() function, which comes from mingwex on Windows. To avoid
    -- linker errors in the absence of a mingwex dependency (see
    -- https://gitlab.haskell.org/ghc/ghc/-/issues/23533 for an example of
    -- this), we depend on mingwex explicitly here.
    --
    -- Other versions of GHC on Windows already depend on mingwex, so we guard
    -- this behind appropriate conditionals.
```
from [unix-time](https://github.com/kazu-yamamoto/unix-time/blob/dadd7805eb043281eda7d90ad42c2bb94951b2d0/unix-time.cabal#L54C1-L62C45).

so, now let's see how to resolve this properly.

**Comment by angerman** [comment]
> ```/nix/store/i7xqxj6xh1hzi06n2vw89i3l3pjk5pbc-x86_64-w64-mingw32-ghc-9.6.2/lib/x86_64-windows-ghc-9.6.2/ghc-prim-0.10.0/HSghc-prim-0.10.0.o: unhandled PEi386 relocation type 14```

That failure is a bit more annoying than it should be.

**Comment by angerman** [comment]
Status update:
- fixed mingwex (https://github.com/input-output-hk/haskell.nix/pull/2032)
- fixed windows relocation issue and wine UNC path issue (https://github.com/input-output-hk/haskell.nix/pull/2034)

Still two more issue:
- [ghc dropped ghci lib support](https://gitlab.haskell.org/ghc/ghc/-/issues/21068), which I think is somewhat misguided, but now we are left with _very_ slow library loading, to the point where this eventually fails. 🎉 
- genprimops is missing and not properly declared as a dependency of `lib:ghc` 🤦

**Comment by angerman** [comment]
Turns out we now try to access `sincos` (a mingwex symbol) from Win32, and of course we haven't loaded that at that point 🤦 That will need an extra symbol. At least we know how to do that.

- `lib:ghc` was solved for now by not depending on reinstalalble lib:ghc. Not ideal but seems to work.
- the ghci issue seems to rather be limitation in cabal https://github.com/haskell/cabal/pull/9220
- now we also have one more issue in haskell.nix which breaks the build of OpenSSL.

**Comment by angerman** [comment]
Ok. I think we got _most_ of it, not all of it yet...
```
[11 of 11] Linking dist/build/trace-dispatcher-examples/trace-dispatcher-examples.exe
/nix/store/fkr9ji0hdzw56y3vk9hhmgzbkhd4v1p8-x86_64-w64-mingw32-binutils-2.35.2/bin/x86_64-w64-mingw32-ld: /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a(lib64_libucrt_extra_a-ucrtbase_compat.o):(.text+0x10): multiple definition of `__getmainargs'; /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmsvcrt.a(libmsvcrt_defs00081.o):(.text+0x0): first defined here
/nix/store/fkr9ji0hdzw56y3vk9hhmgzbkhd4v1p8-x86_64-w64-mingw32-binutils-2.35.2/bin/x86_64-w64-mingw32-ld: /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a(lib64_libucrt_extra_a-ucrtbase_compat.o):(.text+0xf0): multiple definition of `_onexit'; /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmsvcrt.a(libmsvcrt_defs00556.o):(.text+0x0): first defined here
/nix/store/fkr9ji0hdzw56y3vk9hhmgzbkhd4v1p8-x86_64-w64-mingw32-binutils-2.35.2/bin/x86_64-w64-mingw32-ld: /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a(lib64_libucrt_extra_a-ucrtbase_compat.o):(.text+0x130): multiple definition of `_amsg_exit'; /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmsvcrt.a(libmsvcrt_defs00120.o):(.text+0x0): first defined here
/nix/store/fkr9ji0hdzw56y3vk9hhmgzbkhd4v1p8-x86_64-w64-mingw32-binutils-2.35.2/bin/x86_64-w64-mingw32-ld: /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a(lib64_libucrt_extra_a-ucrtbase_compat.o):(.text+0x1e0): multiple definition of `_tzset'; /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmsvcrt.a(libmsvcrt_defs00722.o):(.text+0x0): first defined here
/nix/store/fkr9ji0hdzw56y3vk9hhmgzbkhd4v1p8-x86_64-w64-mingw32-binutils-2.35.2/bin/x86_64-w64-mingw32-ld: /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a(lib64_libucrt_extra_a-ucrtbase_compat.o):(.data+0x18): multiple definition of `__imp__amsg_exit'; /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmsvcrt.a(libmsvcrt_defs00120.o):(.idata$5+0x0): first defined here
/nix/store/fkr9ji0hdzw56y3vk9hhmgzbkhd4v1p8-x86_64-w64-mingw32-binutils-2.35.2/bin/x86_64-w64-mingw32-ld: /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a(lib64_libucrt_extra_a-ucrtbase_compat.o):(.data+0x28): multiple definition of `__imp___getmainargs'; /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmsvcrt.a(libmsvcrt_defs00081.o):(.idata$5+0x0): first defined here
/nix/store/fkr9ji0hdzw56y3vk9hhmgzbkhd4v1p8-x86_64-w64-mingw32-binutils-2.35.2/bin/x86_64-w64-mingw32-ld: /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a(lib64_libucrt_extra_a-ucrtbase_compat.o):(.data+0x70): multiple definition of `__imp__onexit'; /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmsvcrt.a(libmsvcrt_defs00556.o):(.idata$5+0x0): first defined here
collect2: error: ld returned 1 exit status
x86_64-w64-mingw32-ghc: `x86_64-w64-mingw32-cc' failed in phase `Linker'. (Exit code: 1)
```
sigh.

**Comment by angerman** [comment]
So that one I also figured out, it's due to `unix-compat` depending on `msvcrt` yet, ghc now building against `ucrt`.
But that has some other fun issue with mingwex as well :( Lots of
```
Symbol type mismatch.
Symbol _cabs was defined by /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libmingwex.a to be a code symbol.
      yet was defined by /nix/store/jd99w2qxhi9m8p4bmy3mnw31gd9x5ajc-mingw-w64-x86_64-w64-mingw32-10.0.0/lib/libucrt.a to be a data symbol.
```

(and similar) are now blocking the build.

**Comment by angerman** [comment]
See also https://gitlab.haskell.org/ghc/ghc/-/issues/22166

**Review by newhoggy — APPROVED** [review]

**Comment by hamishmack** [comment]
I've squashed and added a TODO comment related to updating [`hlint`](https://github.com/input-output-hk/cardano-node/pull/5439/commits/dcfda75e43564a0f1a2b6befad9ac46c582077f9#diff-6eee708597c86fdab39e71778a57b1b429dabe79fa0e2975860281ae5617aa31R69-R70) (it is currently using an older version as the only one that builds with GHC 9.6.3 kicks up a lot of lint.

**Review by Jimbo4350 — APPROVED** [review]
