### ISSUE TITLE
ping pong demo build problem

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-node#697]
Using stack 2.1.3 on Ubuntu 18.04 I received the following build errors after executing "stack build".
Sorry if this is obvious. I'm just starting to learn Haskell development.

ouroboros-network-framework      > Building executable 'demo-ping-pong' for ouroboros-network-framework-0.1.0.0..
ouroboros-network-framework      > [1 of 2] Compiling Network.TypedProtocol.PingPong.Codec.CBOR
ouroboros-network-framework      > [2 of 2] Compiling Main    
ouroboros-network-framework      > Linking .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/demo-ping-pong/demo-ping-pong ...
ouroboros-network-framework      > /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o):serialisezm0zi2zi1zi0zmFwxkEBqWdesHlC2a9XFtWd_CodecziSerialiseziClass_zdfSerialiseMapzuzdcdecode_info: error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_Decoder_con_info'
ouroboros-network-framework      > /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o):serialisezm0zi2zi1zi0zmFwxkEBqWdesHlC2a9XFtWd_CodecziSerialiseziClass_zdfSerialiseMapzuzdcdecode_info: error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_Decoder_con_info'
[... more similar errors...]

**Comment by shawnim** [comment]
Forgot to mention that this is building the 1.8.0 tag.

**Comment by shawnim** [comment]
Tried with 1.9.1 but still won't build on Ubuntu 18.04.
What am I missing?

ouroboros-network-framework> [2 of 2] Compiling Main
ouroboros-network-framework> Linking .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/demo-ping-pong/demo-ping-pong ...
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o):serialisezm0zi2zi1zi0zmFwxkEBqWdesHlC2a9XFtWd_CodecziSerialiseziClass_zdfSerialiseMapzuzdcdecode_info: error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_Decoder_con_info'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o):serialisezm0zi2zi1zi0zmFwxkEBqWdesHlC2a9XFtWd_CodecziSerialiseziClass_zdfSerialiseMapzuzdcdecode_info: error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_Decoder_con_info'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o):serialisezm0zi2zi1zi0zmFwxkEBqWdesHlC2a9XFtWd_CodecziSerialiseziClass_zdfSerialiseIntMapzuzdcdecode_info: error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_Decoder_con_info'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o):serialisezm0zi2zi1zi0zmFwxkEBqWdesHlC2a9XFtWd_CodecziSerialiseziClass_zdfSerialiseIntMapzuzdcdecode_info: error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_Decoder_con_info'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o)(.text+0x1b8b): error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_zdfApplicativeDecoderzuzdcliftA2_closure'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o)(.text+0x1b95): error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_zdfApplicativeDecoderzuzdcpure_closure'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o)(.text+0x1d53): error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_zdfApplicativeDecoderzuzdcliftA2_closure'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o)(.text+0x1d5d): error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_zdfApplicativeDecoderzuzdcpure_closure'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o)(.text+0x25ff): error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_zdfApplicativeDecoderzuzdcliftA2_closure'
ouroboros-network-framework> /home/shawn/.stack/snapshots/x86_64-linux/9a74558ec27b3341252693aaedb04f5d5cb773cb18d190aeaaca4ea13c222c20/8.6.5/lib/x86_64-linux-ghc-8.6.5/serialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd/libHSserialise-0.2.1.0-FwxkEBqWdesHlC2a9XFtWd.a(Class.o)(.text+0x260c): error: undefined reference to 'cborgzm0zi2zi2zi1zmCPTBBL2ce7IyDD3kGHixI_CodecziCBORziDecoding_zdfApplicativeDecoderzuzdcpure_closure'
ouroboros-network-framework> collect2: error: ld returned 1 exit status
ouroboros-network-framework> `gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package ouroboros-network-framework-0.1.0.0 using:
      /home/shawn/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build --ghc-options ""
    Process exited with code: ExitFailure 1


--  While building package cardano-crypto-wrapper-1.3.0 using:
      /home/shawn/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build --ghc-options ""
    Process exited with code: ExitFailure 1


--  While building package small-steps-0.1.0.0 using:
      /home/shawn/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build --ghc-options ""
    Process exited with code: ExitFailure 1

**Comment by coot** [comment]
You might need to remove your `.stack-work` directory, or try `cabal build` - most of us use it with a great success.

**Comment by shawnim** [comment]
I switched to building with cabal and now I get the following version conflict when building 1.9.3.
Looks like the version of base is newer than the maximum version specified by Win32-network.
I'm not sure why it's building Win32-network on UBuntu.
Any advice on this?

$ cabal build
Warning: Requested index-state2020-01-31T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2020-01-30T23:28:20Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: Win32-network-0.1.0.0 (user goal)
[__1] next goal: base (dependency of Win32-network)
[__1] rejecting: base-4.13.0.0/installed-4.1... (conflict: Win32-network =>
base>=4.5 && <4.13)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: Win32-network, base)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, Win32-network

**Comment by karknu** [comment]
I suspect that you're using the wrong ghc version. You should use ghc 8.6.5 when building.

**Comment by shawnim** [comment]
It would help if there were clear instructions on how to setup a correct compila
tion environment on Ubuntu.
I installed haskell platform from the haskell website.
First the Ubuntu version which was too old and now the generic version which see
ms to be too new.

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3

**Comment by karknu** [comment]
Take a look at https://github.com/input-output-hk/cardano-node/blob/master/doc/building-running.md . The instructions has improved since you filed this ticket.

**Comment by shawnim** [comment]
Thanks for the reference to the update instructions.  That was very helpful.
Everything is building great now!
It would be good if there was a link to that page in the README.md file.
Also, I noticed that the usage message for chairman has 2 descriptions and the s
econd one misspells Shelley.

$ chairman --help
Chairman sits in a room full of Shelley nodes, and checks if they are all
behaving ...

Usage: chairman (-t|--timeout Time) [-p|--require-progress Blocks]
                --socket-path FILEPATH --config NODE-CONFIGURATION 
                [--signing-key FILEPATH] [--delegation-certificate FILEPATH]
  Chairman Shelly application checks if Shelly nodes find consensus.
